# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@~11.2.14
    npm install

  displayName: 'npm install'
  workingDirectory: TTSSWeb/TTSSWebClient/

- script: ng build --prod
  displayName: 'Build Angular for Prod'
  workingDirectory: TTSSWeb/TTSSWebClient/

- script: dotnet publish -c Release
  displayName: 'dotnet publish Release'
  workingDirectory: TTSSWeb
- script: mkdir -p Output && cp azure-publish.sh Output/azure-publish.sh && tar -czf Output/artifact.tar.gz -C TTSSWeb/bin/Release/netcoreapp2.2/publish .
  displayName: 'Move results to Output dir'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: vps_conn
    sourceFolder: Output
    targetFolder: /home/azure/deploy_temp
    cleanTargetFolder: true
- task: SSH@0
  inputs:
    sshEndpoint: vps_conn
    runOptions: 'script'
    scriptPath: 'azure-publish.sh'
    args: ttss