# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'vps2.dszymanski.pl ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH8OAo3PGS3fXzge6NQU3k81GKN6nJ00chkk1UTsnaROMFiB7Dr47+97cMGNos2R8imwc9ghJSt/oPzcCgiH4Jk='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD0vDpBEo2BnwlKbRFcLd8MfO1sPnLUnWTuF9D5+CG8C4GqOYoqHgDZC/ZrEFJHdd5xuTeQFBW3/L+HJG7ruKSCJqn4bJdbGtISUdjxhv5geuixt5v0HIOTF81IY3VAS2MPVKgKM9cba05E8GDQan9h4Mna0JXtwT8iibvFpvv9ZCDDuiJHE5wGBCGX1OGm8TtWChdOkxO6oGqFfNsrluzSvf8bPVm9vn0xPcqDseRsjMkE102+AJGMOBV+3b0EBb+73z55GvD0ZUWtQ1phM/IkUaLorxK9RjjFCm/BYlSJTgsc++HW/xYXOF+vL9DZDBmDvYYW2DgrBPX6C1hBx2CZ5oCvN43kbeKsQIwmUE25ZmFrvJlrAuRfoBiDJZzml5bdGkiDh69Z4Avi23iVq3TKos9uPp41OpFgKDSpGKItlbYKtWaK8+npPAWv91TUxXeulOaXe3vGwhAGF1uLGMnzCyoVWPxFMbWQeTrfLcOlwGkZ5Rne0+CjKxRNr0gDjIKngNjZ82n3K7eJVdBbrOfDBqz+Bl26EtMUrIlPe49X0Oc//g2ALJr1DfA899aktEkKibyJGDxtY8V9A71vc369DFuBomLtX1pNEExu5ukEcf/CQTY10ROI5ID9wHrDbGWZoZ72DGkuq+ET4qYKMIVqbmpNBUT5FoSFe4VAwavQDQ== root@dszymanskimain'
    sshKeySecureFile: 'vpsssh'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'
  workingDirectory: TTSSWeb/TTSSWebClient/

- script: ng build --prod
  displayName: 'Build Angular for Prod'
  workingDirectory: TTSSWeb/TTSSWebClient/

- script: dotnet publish -c ${{parameters.buildConf}}
  displayName: 'dotnet publish ${{parameters.buildConf}}'
  workingDirectory: TTSSWeb
- script: mkdir -p Output && tar -czf Output/artifact.tar.gz -C TTSSWeb/bin/${{parameters.buildConf}}/netcoreapp2.2/publish .
  displayName: 'Move results to Output dir'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: vps_conn
    sourceFolder: Output
    targetFolder: /home/azure/deploy_temp
    cleanTargetFolder: true
- task: SSH@0
  inputs:
    sshEndpoint: vps_conn
    runOptions: 'script'
    scriptPath: 'azure-publish.sh'
    args: ${{parameters.svcName}}